name: Build
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      is-release:
        description: 'Publish release to Modrinth, Curseforge and Github'
        required: false
        default: false
        type: boolean
      dry-run:
        description: 'Dry Run the release, only send Discord Webhook'
        required: false
        default: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 25
        run: echo "JAVA_HOME=$JAVA_HOME_25_X64" >> "$GITHUB_ENV"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: ${{ inputs.is-release }}
          cache-read-only: false

      - name: Apply Spotless
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: ./gradlew spotlessApply

      - name: Data Generation
        run: ./gradlew runClientData

      - name: Build
        run: ./gradlew build

      - name: Maven Release
        if: ${{ inputs.is-release && !inputs.dry-run }}
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
        run: ./gradlew prismPublishMaven

      - name: Publish
        if: ${{ inputs.is-release }}
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew prismPublishAll -Pprism.publishDryRun=${{ inputs.dry-run }}
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-jars
          path: |
            build/libs/*.jar
          if-no-files-found: error
          retention-days: 1
